AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager for Application

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name (dev/prod)

  AppName:
    Type: String
    Default: myapp
    Description: Application name

Conditions:
  IsDev: !Equals [!Ref EnvironmentName, 'dev']
  IsProd: !Equals [!Ref EnvironmentName, 'prod']

Resources:
  # DocumentDB認証情報用のシークレット
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AppName}-${EnvironmentName}-documentdb-credentials
      Description: !Sub DocumentDB credentials for ${AppName}-${EnvironmentName}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-${EnvironmentName}-documentdb-credentials
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  DBSecretArn:
    Description: ARN of the DocumentDB credentials secret
    Value: !Ref DBSecret
    Export:
      Name: !Sub ${EnvironmentName}-DocumentDBSecretArn 