AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC
Resources:
  GithubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      # dummy value (work well)
      ThumbprintList:
        - "6938fd4d98bab03faadb97b34396831e3780aea1"

  GithubDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubDeployRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidcProvider
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub":
                  - "repo:<user>/<repository>"
      Policies:
        - PolicyName: GithubDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - amplify:StartDeployment
                  - amplify:GetApp
                  - amplify:GetBranch
                  - s3:PutObject
                  - s3:GetObject
                Effect: Allow
                Resource: "*"
